name: rtouch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  curved_navigation_bar: ^1.0.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_pannable_rating_bar: ^2.7.2+1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  go_router: ^14.3.0
  google_maps_flutter: ^2.9.0
  google_maps_flutter_android: ^2.14.10
  google_maps_flutter_ios: ^2.13.1
  google_maps_flutter_platform_interface: ^2.9.5
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  story_view: ^0.16.5
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/videos/splash.mp4
    - assets/icons/logo_1.png
    - assets/icons/stc.png
    - assets/icons/mada.png
    - assets/icons/master.png
    - assets/icons/circle_move_true.png
    - assets/icons/web_icon.png
    - assets/icons/circle_move.png
    - assets/icons/filter_alt.png
    - assets/icons/needle.png
    - assets/icons/folder.png
    - assets/icons/measuring_tape.png
    - assets/icons/profile_woman.png
    - assets/icons/profile_woman2.png

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/font/font.ttf
        - asset: assets/font/font_bold.ttf
          weight: 700
        - asset: assets/font/font_extra_bold.ttf
          weight: 800
        - asset: assets/font/font_light.ttf
          weight: 300

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_1.png"
