name: rtouch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^14.3.0
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/videos/splash.mp4
    - assets/img/ll.jpg

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/font/font.ttf
        - asset: assets/font/font_bold.ttf
          weight: 700
        - asset: assets/font/font_extra_bold.ttf
          weight: 800
        - asset: assets/font/font_light.ttf
          weight: 300
